version: '3.8'

services:
  exam_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    stop_grace_period: 10s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge